apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: elasticsearch
    
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:5.6-alpine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "768Mi"
              cpu: "100m"
          ports:
            - containerPort: 9200
              name: "p9200"
            - containerPort: 9300
              name: "p9300"
              
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: "p9200"
  - protocol: TCP
    port: 9300
    targetPort: 9300
    name: "p9300"