apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  namespace: default
  labels:
    app: reservation
spec:
  replicas: 1
  revisionHistoryLimit: 1 # how many old ReplicaSets for this Deployment you want to retain, https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy
  selector:
    matchLabels:
      app: reservation
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: reservation
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:        
        - name: reservation
          image: weihanli/activityreservation:dev
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /Health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 60
          ports:
            - containerPort: 80
          env:
            - name: Reservation_AppSettings__DbType
              value: InMemory
            - name: Reservation_ConnectionStrings__ElasticSearch
              value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: activityreservation
spec:
  selector:
    app: activityreservation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31220
  type: NodePort
